# Aletheia Lint Workflow
name: Lint

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  lint-python:
    name: Lint Python Code
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install linters
        run: |
          pip install ruff mypy black isort

      - name: Run Ruff (sidecar)
        working-directory: sidecar
        run: ruff check .

      - name: Run Ruff (cli)
        working-directory: cli
        run: ruff check .

      - name: Check Black formatting (sidecar)
        working-directory: sidecar
        run: black --check .

      - name: Check Black formatting (cli)
        working-directory: cli
        run: black --check .

      - name: Check isort (sidecar)
        working-directory: sidecar
        run: isort --check-only .

      - name: Check isort (cli)
        working-directory: cli
        run: isort --check-only .

      - name: Run mypy (sidecar)
        working-directory: sidecar
        run: mypy aletheia_sidecar/ --ignore-missing-imports

      - name: Run mypy (cli)
        working-directory: cli
        run: mypy aletheia_cli/ --ignore-missing-imports

  lint-typescript:
    name: Lint TypeScript Code
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        working-directory: extension/vscode
        run: pnpm install

      - name: Run ESLint
        working-directory: extension/vscode
        run: pnpm lint

      - name: Check TypeScript compilation
        working-directory: extension/vscode
        run: pnpm compile

  lint-json-schemas:
    name: Validate JSON Schemas
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install ajv-cli
        run: npm install -g ajv-cli

      - name: Validate schemas
        run: |
          for schema in shared_schemas/*.schema.json; do
            echo "Validating $schema"
            ajv compile -s "$schema" --strict=true
          done

  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          severity: 'CRITICAL,HIGH'

      - name: Run Bandit (Python security)
        run: |
          pip install bandit
          bandit -r sidecar/aletheia_sidecar cli/aletheia_cli -ll
