# Aletheia Release Workflow
name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., 1.0.0)'
        required: true
        type: string

permissions:
  contents: write
  packages: write

jobs:
  build-sidecar:
    name: Build Sidecar Docker Image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}/sidecar
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: packaging/docker/sidecar.Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64

  build-cli:
    name: Build CLI Packages
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install build tools
        run: pip install build twine

      - name: Build package
        working-directory: cli
        run: python -m build

      - name: Upload to PyPI
        working-directory: cli
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: twine upload dist/*

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cli-dist
          path: cli/dist/

  build-extension:
    name: Build VS Code Extension
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        working-directory: extension/vscode
        run: pnpm install

      - name: Install vsce
        run: npm install -g @vscode/vsce

      - name: Build VSIX
        working-directory: extension/vscode
        run: vsce package --out ../../packaging/vsix/

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: vsix
          path: packaging/vsix/*.vsix

      - name: Publish to Marketplace
        working-directory: extension/vscode
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
        run: vsce publish -p $VSCE_PAT

  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: [build-sidecar, build-cli, build-extension]

    steps:
      - uses: actions/checkout@v4

      - name: Download CLI artifacts
        uses: actions/download-artifact@v4
        with:
          name: cli-dist
          path: dist/cli

      - name: Download VSIX artifacts
        uses: actions/download-artifact@v4
        with:
          name: vsix
          path: dist/vsix

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/cli/*
            dist/vsix/*
          generate_release_notes: true
          draft: false
          prerelease: ${{ contains(github.ref, 'alpha') || contains(github.ref, 'beta') }}
